version: '3.8'

services:
  pomodoro:
    build: .
    container_name: pomodoro-app
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=false
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-super_secret_default_key}
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
    volumes:
      - ./data:/app/data  # Сохраняем базу данных SQLite при перезапусках!