server {
    listen 80;
    server_name 25x5.ru www.25x5.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}